### ISSUE TITLE
Get-UMSFirmware -Computername IGELSERVER-WebSession $WebSession results in Error

### ISSUE THREAD

**Issue by Hoeflers** [IGEL-Community/PSIGEL#47]
Ausnahme beim Aufrufen von ".ctor" mit 1 Argument(en):  "Die Eingabezeichenfolge hat das falsche Format."
In C:\windows\system32\WindowsPowerShell\v1.0\Modules\PSIGEL\Public\Get-UMSFirmware.ps1:59 Zeichen:7
+       $Properties = [ordered]@{
+       ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

**Comment by falkheiland** [comment]
please use branch with name release-v0.10.0
https://github.com/IGEL-Community/PSIGEL/tree/release-v0.10.0

this error occurs if you have a non stadard firmware (private build) which does not follow semver used im .net. this was changed in above branch.

**Comment by Hoeflers** [comment]
sorry for the late reply and the inconvenience.
But I used the release and still have the same problems.
Is there anything else I need to consider?

**Comment by falkheiland** [comment]
what is your output from that command:

```
 ((((Get-Command -Module PSIGEL -Name Get-UMSFirmware).Definition).Split("`r`n"))).where{$_ -match 'Version'}
 ```

**Comment by falkheiland** [comment]
just checked again - please use the master branch, not the 0.10. one - my mistake (did not have a look into it for a while).
the master branch is the most current - but there is no official version out for a release.

in the master branch there is 

https://github.com/IGEL-Community/PSIGEL/blob/33fa275e9515052a53106171af77962d31ec0b2d/PSIGEL/Public/Get-UMSFirmware.ps1#L62

which just takes the string from the api response now.
