### ISSUE TITLE
Handle Non Ascii Characters correctly

### ISSUE THREAD

**Issue by lhpitn** [IGEL-Community/PSIGEL#48]
Hi,

thanks a lot for this toolset, i cant imagine why the UMS Deveolopers missed a simple csv export of the devices list...

One thing we stumbled across here using German umlauts and so in description fields 

````
[...]
Site                      : BÃ¼ro ******
[...]
````

Such characters are not handled with the right encoding, would be grate inf that could be fixed.

thanks a lot and keep up the good work

**Comment by lhpitn** [comment]
it schemas like the output is utf8 (one char became two chars, but handled as iso-something, unfortunately they get replaced with ?? when saving it as csv so a simple search-replace for all 4 (or 7 if you include capitals) cases in german language cant help..)

**Comment by HCRitter** [comment]
@lhpitn could you please be so kind and telling us which command you have used?

**Comment by lhpitn** [comment]
``Get-UMSDevice -Computername localhost -WebSession $WebSession -Filter details``

**Comment by Constey** [comment]
same here. utf8 is not properly used which brings problems with german umlauts

**Comment by falkheiland** [comment]
https://github.com/IGEL-Community/PSIGEL/pull/38
