### ISSUE TITLE
Get-UMSStatus dosnt work

### ISSUE THREAD

**Issue by lhpitn** [IGEL-Community/PSIGEL#49]
I tried this from the example but it didnt work

```
> Get-UMSStatus -Computername localhost -WebSession $WebSession
Ausnahme beim Aufrufen von ".ctor" mit 1 Argument(en):  "Der Versionszeichenfolgeteil war entweder zu kurz oder zu
lang."
In C:\Program Files\WindowsPowerShell\Modules\PSIGEL\0.10.0\Public\Get-UMSStatus.ps1:45 Zeichen:7
+       $Properties = [ordered]@{
+       ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```

not important for me, cause we only needed umsDevice and umsDeviceDirectory but it lookes like they updated the the API on the UMS version we have here (Version 12)

keep up the good work

**Comment by lhpitn** [comment]
rough translation of german error message:

Exception when calling ".ctor" with 1 argument(s): "The version string part was either too short or too
long."
In C:\Program Files\WindowsPowerShell\Modules\PSIGEL\0.10.0\Public\Get-UMSStatus.ps1:45 characters:7

**Comment by falkheiland** [comment]
igel degraded that api endpoint, there is nothing i can do here.
